from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI
from concurrent.futures import ThreadPoolExecutor

import polars as pl
from ingest import build_index, load_faq_data
from evaluation_utils import RAGWithUsage, calc_price, calc_total_price, llm_structured_retry, map_progress

from pydantic import BaseModel, Field
from typing import Literal

load_dotenv()
openai_client = OpenAI()

data_paths = Path("lesson_4/data")

df_answers = pl.read_csv(data_paths / "rag-answers-new.csv")
answers = df_answers.to_dicts()

class AnswerEvaluation(BaseModel):
    reasoning: str = Field(
        description="Reasoning about the quality of the answer."
    )
    score: Literal["good", "bad"] = Field(
        description="'good' if the answer is correct and complete, 'bad' otherwise."
    )

aqa_judge_instructions = """
You are an expert evaluator. You will be given:
1. A question from a student
2. The original answer from the FAQ (ground truth)
3. An answer generated by an AI assistant

Your task is to decide if the AI answer is semantically equivalent to
the original answer.

Rules:
- The AI answer does NOT need to be word-for-word identical
- It should convey the same key information
- Extra detail is fine as long as the core answer is correct
- Mark 'bad' only if the AI answer is wrong or misses the key point

Be fair and focus on correctness, not style.
""".strip()

aqa_judge_prompt = """
Question:
{question}

Original Answer (ground truth):
{answer_orig}

AI Answer:
{answer_llm}
""".strip()

prompt = aqa_judge_prompt.format(
    question=answers[0]["question"],
    answer_orig=answers[0]["answer_orig"],
    answer_llm=answers[0]["answer_llm"],
)

# print(prompt)
# 
# eval_result, usage = llm_structured_retry(
#     openai_client,
#     aqa_judge_instructions,
#     prompt,
#     AnswerEvaluation,
#     model="gpt-5.4-nano",
#     max_retries=3,
# )
# print(eval_result, usage)

def evaluate_aqa(question, answer_orig, answer_llm, model="gpt-5.4-mini"):
    prompt = aqa_judge_prompt.format(
        question=question,
        answer_orig=answer_orig,
        answer_llm=answer_llm
    )

    result, usage = llm_structured_retry(
        openai_client,
        aqa_judge_instructions,
        prompt,
        AnswerEvaluation,
        model=model,
    )

    return result, usage

eval_result, usage = evaluate_aqa(
    question=answers[0]["question"],
    answer_orig=answers[0]["answer_orig"],
    answer_llm=answers[0]["answer_llm"]
)

# print(eval_result)
def judge_record(rec):
    eval_result, usage = evaluate_aqa(
        question=rec["question"],
        answer_orig=rec["answer_orig"],
        answer_llm=rec["answer_llm"]
    )

    result = {
        "question": rec["question"],
        "document": rec["document"],
        "score": eval_result.score,
        "reasoning": eval_result.reasoning,
    }

    return result, usage
    
# result, usage = judge_record(answers[0])
# print(result)
# print(usage)
# 

with ThreadPoolExecutor(max_workers=6) as pool:
    results = map_progress(pool, answers, judge_record)

evaluations = []
usages = []

for evaluation, usage in results:
    evaluations.append(evaluation)
    usages.append(usage)


df_eval = pl.DataFrame(evaluations)
print(df_eval.sample(10))

print(calc_total_price(usages))